# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ExchangeRateApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
  pod ‘Alamofire’, '~>4.7.2'
  # Pods for ExchangeRateApp

  target 'ExchangeRateAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ExchangeRateAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
